name = "DomainDecomposition"
uuid = "aabdb850-e4f6-11e8-0a7d-7fb1be061a1f"
authors = ["ben-cgi <ben@compgeoinc.com>"]
version = "0.1.0"

[deps]
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
